CREATE TABLE hskcdp_ga.ga_raw_events
(
    event_date Date,
    event_timestamp DateTime,
    event_name String,
    event_params Nullable(String),
    event_previous_timestamp Nullable(DateTime64(6)),
    event_value_in_usd Nullable(Float64),
    event_bundle_sequence_id Nullable(Int32),
    event_server_timestamp_offset Nullable(Int32),
    user_id Nullable(bigint),
    user_pseudo_id Nullable(String),
    privacy_info Nullable(String),
    user_properties Nullable(String),
    user_first_touch_timestamp Nullable(DateTime64(6)),
    user_ltv Nullable(String),
    device Nullable(String),
    geo Nullable(String),
    app_info Nullable(String),
    traffic_source Nullable(String),
    stream_id Nullable(String),
    platform Nullable(String),
    event_dimensions Nullable(Int32),
    ecommerce Nullable(String),
    items Nullable(String),
    collected_traffic_source Nullable(String),
    is_active_user Nullable(Boolean),
    batch_event_index Nullable(Int32),
    batch_page_id Nullable(Int32),
    batch_ordering_id Nullable(Int32),
    session_traffic_source_last_click Nullable(Int32),
    publisher Nullable(Int32)
)
ENGINE = MergeTree()
ORDER BY (event_date, event_timestamp)